language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install nosexcover
  - pip install coveralls
  - python setup.py -q install

script:
  nosetests --with-xcoverage --cover-package vcsi.vcsi

after_success:
  coveralls
