language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install 'coverage<4'
  - pip install nosexcover
  - pip install coveralls

script:
  nosetests --with-xcoverage --cover-package vcsi.vcsi

after_success:
  coveralls
