language: python

python:
  - "3.3"
  - "3.4"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install nosexcover
  - pip install coveralls

script:
  nosetests --with-xcoverage --cover-package vcsi

after_success:
  coveralls
